INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)

set(ARM_COMPILER_PATH /opt/gcc-arm-none-eabi-4_9-2014q4/bin)

set(CMAKE_FIND_ROOT_PATH /opt/gcc-arm-none-eabi-4_9-2014q4)

CMAKE_FORCE_C_COMPILER		(${ARM_COMPILER_PATH}/arm-none-eabi-gcc GNU)
CMAKE_FORCE_CXX_COMPILER	(${ARM_COMPILER_PATH}/arm-none-eabi-g++ GNU)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)